/*
 * generated by Xtext 2.25.0
 */
package fr.imta.semafor;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class FogDslStandaloneSetup extends FogDslStandaloneSetupGenerated {

	public static void doSetup() {
		new FogDslStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
