/*
 * generated by Xtext 2.25.0
 */
package fr.imta.semafor.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import fr.imta.semafor.FogDslRuntimeModule;
import fr.imta.semafor.FogDslStandaloneSetup;
import org.eclipse.xtext.util.Modules2;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class FogDslIdeSetup extends FogDslStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new FogDslRuntimeModule(), new FogDslIdeModule()));
	}
	
}
