<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="ConstrainedProblem" nsURI="http://www.example.org/ConstrainedProblem"
    nsPrefix="ConstrainedProblem">
  <eClassifiers xsi:type="ecore:EClass" name="Problem">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constraints" upperBound="-1"
        eType="#//Constraint" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedobjects" upperBound="-1"
        eType="#//ConstrainedObject" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstrainedObject">
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" eType="#//ConstrainedObjectSchema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedvariables" upperBound="-1"
        eType="#//ConstrainedVariable" containment="true" eOpposite="#//ConstrainedVariable/constrainedobject"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstrainedVariable">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="hint" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="schema" lowerBound="1"
        eType="#//Schema"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedobject" eType="#//ConstrainedObject"
        eOpposite="#//ConstrainedObject/constrainedvariables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Constraint">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="2"
        upperBound="2" eType="#//Expression" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="comparaisonOperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Schema">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="possibleValues" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedobjectschemas"
        lowerBound="1" upperBound="-1" eType="#//ConstrainedObjectSchema" eOpposite="#//ConstrainedObjectSchema/variables"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Expression" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="IntValueExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableExpression" abstract="true"
      eSuperTypes="#//Expression"/>
  <eClassifiers xsi:type="ecore:EClass" name="ComplexExpression" eSuperTypes="#//Expression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="expressions" lowerBound="2"
        upperBound="2" eType="#//Expression"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="arithmeticOperator" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ConstrainedObjectSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="variables" upperBound="-1"
        eType="#//Schema" eOpposite="#//Schema/constrainedobjectschemas"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DirectVariableExpre" eSuperTypes="#//VariableExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedVariable" eType="#//ConstrainedVariable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IndirectVariableExpre" eSuperTypes="#//VariableExpression">
    <eStructuralFeatures xsi:type="ecore:EReference" name="constrainedObject" eType="#//ConstrainedVariable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="variableName" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
