/*
 * generated by Xtext 2.28.0
 */
package fr.imta.semafor.parser.antlr;

import com.google.inject.Inject;
import fr.imta.semafor.parser.antlr.internal.InternalFogDslParser;
import fr.imta.semafor.services.FogDslGrammarAccess;
import org.eclipse.xtext.parser.antlr.AbstractAntlrParser;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

public class FogDslParser extends AbstractAntlrParser {

	@Inject
	private FogDslGrammarAccess grammarAccess;

	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	

	@Override
	protected InternalFogDslParser createParser(XtextTokenStream stream) {
		return new InternalFogDslParser(stream, getGrammarAccess());
	}

	@Override 
	protected String getDefaultRuleName() {
		return "FogResource";
	}

	public FogDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FogDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
