/*
 * generated by Xtext 2.28.0
 */
package fr.imta.semafor.parser.antlr;

import java.io.InputStream;
import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class FogDslAntlrTokenFileProvider implements IAntlrTokenFileProvider {

	@Override
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
		return classLoader.getResourceAsStream("fr/imta/semafor/parser/antlr/internal/InternalFogDsl.tokens");
	}
}
