/*
 * generated by Xtext 2.28.0
 */
package fr.imta.semafor.ide.contentassist.antlr;

import com.google.common.collect.ImmutableMap;
import com.google.inject.Inject;
import com.google.inject.Singleton;
import fr.imta.semafor.ide.contentassist.antlr.internal.InternalFogDslParser;
import fr.imta.semafor.services.FogDslGrammarAccess;
import java.util.Map;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ide.editor.contentassist.antlr.AbstractContentAssistParser;

public class FogDslParser extends AbstractContentAssistParser {

	@Singleton
	public static final class NameMappings {
		
		private final Map<AbstractElement, String> mappings;
		
		@Inject
		public NameMappings(FogDslGrammarAccess grammarAccess) {
			ImmutableMap.Builder<AbstractElement, String> builder = ImmutableMap.builder();
			init(builder, grammarAccess);
			this.mappings = builder.build();
		}
		
		public String getRuleName(AbstractElement element) {
			return mappings.get(element);
		}
		
		private static void init(ImmutableMap.Builder<AbstractElement, String> builder, FogDslGrammarAccess grammarAccess) {
			builder.put(grammarAccess.getFogResourceAccess().getAlternatives_3(), "rule__FogResource__Alternatives_3");
			builder.put(grammarAccess.getFogResourceAccess().getAlternatives_3_2_3(), "rule__FogResource__Alternatives_3_2_3");
			builder.put(grammarAccess.getFogResourceAccess().getAlternatives_3_3_3(), "rule__FogResource__Alternatives_3_3_3");
			builder.put(grammarAccess.getSerivceTypeAccess().getAlternatives_8(), "rule__SerivceType__Alternatives_8");
			builder.put(grammarAccess.getNetworkTypeAccess().getConstraintsAlternatives_10_1_0(), "rule__NetworkType__ConstraintsAlternatives_10_1_0");
			builder.put(grammarAccess.getConstraintAccess().getAlternatives_3(), "rule__Constraint__Alternatives_3");
			builder.put(grammarAccess.getConstraintAccess().getExpressionAlternatives_3_0_0(), "rule__Constraint__ExpressionAlternatives_3_0_0");
			builder.put(grammarAccess.getConstraintAccess().getExpressionAlternatives_3_1_2_0(), "rule__Constraint__ExpressionAlternatives_3_1_2_0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getConstraintsAlternatives_12_1_0(), "rule__NetworkLinksType__ConstraintsAlternatives_12_1_0");
			builder.put(grammarAccess.getNetworkClassConstraintAccess().getAlternatives(), "rule__NetworkClassConstraint__Alternatives");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getAlternatives(), "rule__BandwidthConstraint__Alternatives");
			builder.put(grammarAccess.getReplicasConstraintAccess().getAlternatives_3(), "rule__ReplicasConstraint__Alternatives_3");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getAlternatives_3(), "rule__RuntimesConstraint__Alternatives_3");
			builder.put(grammarAccess.getDiskConstraintAccess().getAlternatives_3(), "rule__DiskConstraint__Alternatives_3");
			builder.put(grammarAccess.getMemoryConsraintAccess().getAlternatives_3(), "rule__MemoryConsraint__Alternatives_3");
			builder.put(grammarAccess.getCpuConstraintAccess().getAlternatives_3(), "rule__CpuConstraint__Alternatives_3");
			builder.put(grammarAccess.getValueAccess().getAlternatives(), "rule__Value__Alternatives");
			builder.put(grammarAccess.getEStringAccess().getAlternatives(), "rule__EString__Alternatives");
			builder.put(grammarAccess.getMultiplicityOperatorAccess().getAlternatives(), "rule__MultiplicityOperator__Alternatives");
			builder.put(grammarAccess.getTransportProtocolAccess().getAlternatives(), "rule__TransportProtocol__Alternatives");
			builder.put(grammarAccess.getNetworkClassEnumAccess().getAlternatives(), "rule__NetworkClassEnum__Alternatives");
			builder.put(grammarAccess.getHealthStatusAccess().getAlternatives(), "rule__HealthStatus__Alternatives");
			builder.put(grammarAccess.getCpuArchitectureAccess().getAlternatives(), "rule__CpuArchitecture__Alternatives");
			builder.put(grammarAccess.getComparaisonOperatorAccess().getAlternatives(), "rule__ComparaisonOperator__Alternatives");
			builder.put(grammarAccess.getFogResourceAccess().getGroup(), "rule__FogResource__Group__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_0(), "rule__FogResource__Group_3_0__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_1(), "rule__FogResource__Group_3_1__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_2(), "rule__FogResource__Group_3_2__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_3(), "rule__FogResource__Group_3_3__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_4(), "rule__FogResource__Group_3_4__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_5(), "rule__FogResource__Group_3_5__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_6(), "rule__FogResource__Group_3_6__0");
			builder.put(grammarAccess.getFogResourceAccess().getGroup_3_7(), "rule__FogResource__Group_3_7__0");
			builder.put(grammarAccess.getVirtualNodeAccess().getGroup(), "rule__VirtualNode__Group__0");
			builder.put(grammarAccess.getVirtualNodeAccess().getGroup_2(), "rule__VirtualNode__Group_2__0");
			builder.put(grammarAccess.getVirtualNodeAccess().getGroup_5(), "rule__VirtualNode__Group_5__0");
			builder.put(grammarAccess.getVirtualNodeAccess().getGroup_16(), "rule__VirtualNode__Group_16__0");
			builder.put(grammarAccess.getFogSystemAccess().getGroup(), "rule__FogSystem__Group__0");
			builder.put(grammarAccess.getFogAreaAccess().getGroup(), "rule__FogArea__Group__0");
			builder.put(grammarAccess.getAttributeTypeAccess().getGroup(), "rule__AttributeType__Group__0");
			builder.put(grammarAccess.getAttributeTypeAccess().getGroup_6(), "rule__AttributeType__Group_6__0");
			builder.put(grammarAccess.getAttributeTypeAccess().getGroup_6_2(), "rule__AttributeType__Group_6_2__0");
			builder.put(grammarAccess.getPhysicalNodeAccess().getGroup(), "rule__PhysicalNode__Group__0");
			builder.put(grammarAccess.getPhysicalNodeAccess().getGroup_2(), "rule__PhysicalNode__Group_2__0");
			builder.put(grammarAccess.getPhysicalNodeAccess().getGroup_8(), "rule__PhysicalNode__Group_8__0");
			builder.put(grammarAccess.getPhysicalNodeAccess().getGroup_16(), "rule__PhysicalNode__Group_16__0");
			builder.put(grammarAccess.getAttributeValueUnitAccess().getGroup(), "rule__AttributeValueUnit__Group__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup(), "rule__Application__Group__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup_2(), "rule__Application__Group_2__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup_5(), "rule__Application__Group_5__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup_10(), "rule__Application__Group_10__0");
			builder.put(grammarAccess.getApplicationAccess().getGroup_13(), "rule__Application__Group_13__0");
			builder.put(grammarAccess.getConnectorTypeAccess().getGroup(), "rule__ConnectorType__Group__0");
			builder.put(grammarAccess.getConnectorTypeAccess().getGroup_4(), "rule__ConnectorType__Group_4__0");
			builder.put(grammarAccess.getConnectorTypeAccess().getGroup_7(), "rule__ConnectorType__Group_7__0");
			builder.put(grammarAccess.getConnectorTypeAccess().getGroup_10(), "rule__ConnectorType__Group_10__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup(), "rule__SerivceType__Group__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_2(), "rule__SerivceType__Group_2__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_5(), "rule__SerivceType__Group_5__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_8_0(), "rule__SerivceType__Group_8_0__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_8_0_1(), "rule__SerivceType__Group_8_0_1__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_8_1(), "rule__SerivceType__Group_8_1__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_8_1_2(), "rule__SerivceType__Group_8_1_2__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_11(), "rule__SerivceType__Group_11__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_11_2(), "rule__SerivceType__Group_11_2__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_11_3(), "rule__SerivceType__Group_11_3__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_12(), "rule__SerivceType__Group_12__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_12_4(), "rule__SerivceType__Group_12_4__0");
			builder.put(grammarAccess.getSerivceTypeAccess().getGroup_13(), "rule__SerivceType__Group_13__0");
			builder.put(grammarAccess.getSoftwarePackageAccess().getGroup(), "rule__SoftwarePackage__Group__0");
			builder.put(grammarAccess.getSoftwarePackageAccess().getGroup_7(), "rule__SoftwarePackage__Group_7__0");
			builder.put(grammarAccess.getPortsConstraintAccess().getGroup(), "rule__PortsConstraint__Group__0");
			builder.put(grammarAccess.getNetworkPortAccess().getGroup(), "rule__NetworkPort__Group__0");
			builder.put(grammarAccess.getNetworkTypeAccess().getGroup(), "rule__NetworkType__Group__0");
			builder.put(grammarAccess.getNetworkTypeAccess().getGroup_2(), "rule__NetworkType__Group_2__0");
			builder.put(grammarAccess.getNetworkTypeAccess().getGroup_5(), "rule__NetworkType__Group_5__0");
			builder.put(grammarAccess.getNetworkTypeAccess().getGroup_10(), "rule__NetworkType__Group_10__0");
			builder.put(grammarAccess.getConstraintAccess().getGroup(), "rule__Constraint__Group__0");
			builder.put(grammarAccess.getConstraintAccess().getGroup_3_1(), "rule__Constraint__Group_3_1__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup(), "rule__NetworkLinksType__Group__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_7(), "rule__NetworkLinksType__Group_7__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_12(), "rule__NetworkLinksType__Group_12__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_15(), "rule__NetworkLinksType__Group_15__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_15_2(), "rule__NetworkLinksType__Group_15_2__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_16(), "rule__NetworkLinksType__Group_16__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_16_2(), "rule__NetworkLinksType__Group_16_2__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_17(), "rule__NetworkLinksType__Group_17__0");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getGroup_18(), "rule__NetworkLinksType__Group_18__0");
			builder.put(grammarAccess.getNetworkClassConstraintAccess().getGroup_0(), "rule__NetworkClassConstraint__Group_0__0");
			builder.put(grammarAccess.getNetworkClassConstraintAccess().getGroup_1(), "rule__NetworkClassConstraint__Group_1__0");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getGroup_0(), "rule__BandwidthConstraint__Group_0__0");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getGroup_0_2(), "rule__BandwidthConstraint__Group_0_2__0");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getGroup_1(), "rule__BandwidthConstraint__Group_1__0");
			builder.put(grammarAccess.getIpRangeConstraintAccess().getGroup(), "rule__IpRangeConstraint__Group__0");
			builder.put(grammarAccess.getRangeExpressionAccess().getGroup(), "rule__RangeExpression__Group__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup(), "rule__VirtualNodeType__Group__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_2(), "rule__VirtualNodeType__Group_2__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_5(), "rule__VirtualNodeType__Group_5__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_8(), "rule__VirtualNodeType__Group_8__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_9(), "rule__VirtualNodeType__Group_9__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_9_3(), "rule__VirtualNodeType__Group_9_3__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_17(), "rule__VirtualNodeType__Group_17__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_22(), "rule__VirtualNodeType__Group_22__0");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getGroup_25(), "rule__VirtualNodeType__Group_25__0");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getGroup(), "rule__PhysicalNodeType__Group__0");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getGroup_0(), "rule__PhysicalNodeType__Group_0__0");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getGroup_0_2(), "rule__PhysicalNodeType__Group_0_2__0");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getGroup_0_5(), "rule__PhysicalNodeType__Group_0_5__0");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getGroup_13(), "rule__PhysicalNodeType__Group_13__0");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getGroup_16(), "rule__PhysicalNodeType__Group_16__0");
			builder.put(grammarAccess.getReplicasConstraintAccess().getGroup(), "rule__ReplicasConstraint__Group__0");
			builder.put(grammarAccess.getReplicasConstraintAccess().getGroup_3_1(), "rule__ReplicasConstraint__Group_3_1__0");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getGroup(), "rule__RuntimesConstraint__Group__0");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getGroup_3_0(), "rule__RuntimesConstraint__Group_3_0__0");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getGroup_3_1(), "rule__RuntimesConstraint__Group_3_1__0");
			builder.put(grammarAccess.getDiskConstraintAccess().getGroup(), "rule__DiskConstraint__Group__0");
			builder.put(grammarAccess.getDiskConstraintAccess().getGroup_3_1(), "rule__DiskConstraint__Group_3_1__0");
			builder.put(grammarAccess.getMemoryConsraintAccess().getGroup(), "rule__MemoryConsraint__Group__0");
			builder.put(grammarAccess.getMemoryConsraintAccess().getGroup_3_1(), "rule__MemoryConsraint__Group_3_1__0");
			builder.put(grammarAccess.getCpuConstraintAccess().getGroup(), "rule__CpuConstraint__Group__0");
			builder.put(grammarAccess.getCpuConstraintAccess().getGroup_3_1(), "rule__CpuConstraint__Group_3_1__0");
			builder.put(grammarAccess.getTagAccess().getGroup(), "rule__Tag__Group__0");
			builder.put(grammarAccess.getVirtualNodeAccess().getNameAssignment_2_2(), "rule__VirtualNode__NameAssignment_2_2");
			builder.put(grammarAccess.getVirtualNodeAccess().getTagsAssignment_5_1(), "rule__VirtualNode__TagsAssignment_5_1");
			builder.put(grammarAccess.getVirtualNodeAccess().getIsInstanceOfAssignment_8(), "rule__VirtualNode__IsInstanceOfAssignment_8");
			builder.put(grammarAccess.getVirtualNodeAccess().getHostingNodeAssignment_13(), "rule__VirtualNode__HostingNodeAssignment_13");
			builder.put(grammarAccess.getVirtualNodeAccess().getHostedVirtualNodesAssignment_16_1(), "rule__VirtualNode__HostedVirtualNodesAssignment_16_1");
			builder.put(grammarAccess.getVirtualNodeAccess().getAttributesAssignment_17(), "rule__VirtualNode__AttributesAssignment_17");
			builder.put(grammarAccess.getFogSystemAccess().getNameAssignment_2(), "rule__FogSystem__NameAssignment_2");
			builder.put(grammarAccess.getFogAreaAccess().getNameAssignment_2(), "rule__FogArea__NameAssignment_2");
			builder.put(grammarAccess.getFogAreaAccess().getFogsystemAssignment_5(), "rule__FogArea__FogsystemAssignment_5");
			builder.put(grammarAccess.getAttributeTypeAccess().getNameAssignment_2(), "rule__AttributeType__NameAssignment_2");
			builder.put(grammarAccess.getAttributeTypeAccess().getValueTypeAssignment_5(), "rule__AttributeType__ValueTypeAssignment_5");
			builder.put(grammarAccess.getAttributeTypeAccess().getUnitofmeasurmentAssignment_6_2_1(), "rule__AttributeType__UnitofmeasurmentAssignment_6_2_1");
			builder.put(grammarAccess.getPhysicalNodeAccess().getNameAssignment_2_2(), "rule__PhysicalNode__NameAssignment_2_2");
			builder.put(grammarAccess.getPhysicalNodeAccess().getFogareaAssignment_5(), "rule__PhysicalNode__FogareaAssignment_5");
			builder.put(grammarAccess.getPhysicalNodeAccess().getTagsAssignment_8_1(), "rule__PhysicalNode__TagsAssignment_8_1");
			builder.put(grammarAccess.getPhysicalNodeAccess().getIsInstanceOfAssignment_11(), "rule__PhysicalNode__IsInstanceOfAssignment_11");
			builder.put(grammarAccess.getPhysicalNodeAccess().getHostedVirtualNodesAssignment_16_1(), "rule__PhysicalNode__HostedVirtualNodesAssignment_16_1");
			builder.put(grammarAccess.getPhysicalNodeAccess().getAttributesAssignment_17(), "rule__PhysicalNode__AttributesAssignment_17");
			builder.put(grammarAccess.getAttributeValueUnitAccess().getInstanceOfAssignment_0(), "rule__AttributeValueUnit__InstanceOfAssignment_0");
			builder.put(grammarAccess.getAttributeValueUnitAccess().getValueAssignment_2(), "rule__AttributeValueUnit__ValueAssignment_2");
			builder.put(grammarAccess.getApplicationAccess().getNameAssignment_2_2(), "rule__Application__NameAssignment_2_2");
			builder.put(grammarAccess.getApplicationAccess().getTagsAssignment_5_1(), "rule__Application__TagsAssignment_5_1");
			builder.put(grammarAccess.getApplicationAccess().getServiceTypesAssignment_10_3(), "rule__Application__ServiceTypesAssignment_10_3");
			builder.put(grammarAccess.getApplicationAccess().getConnectortypesAssignment_13_1(), "rule__Application__ConnectortypesAssignment_13_1");
			builder.put(grammarAccess.getConnectorTypeAccess().getNameAssignment_0(), "rule__ConnectorType__NameAssignment_0");
			builder.put(grammarAccess.getConnectorTypeAccess().getSourceServicesAssignment_4_1(), "rule__ConnectorType__SourceServicesAssignment_4_1");
			builder.put(grammarAccess.getConnectorTypeAccess().getTargetServicesAssignment_7_1(), "rule__ConnectorType__TargetServicesAssignment_7_1");
			builder.put(grammarAccess.getConnectorTypeAccess().getConstraintsAssignment_10_1(), "rule__ConnectorType__ConstraintsAssignment_10_1");
			builder.put(grammarAccess.getSerivceTypeAccess().getNameAssignment_2_2(), "rule__SerivceType__NameAssignment_2_2");
			builder.put(grammarAccess.getSerivceTypeAccess().getTagsAssignment_5_1(), "rule__SerivceType__TagsAssignment_5_1");
			builder.put(grammarAccess.getSerivceTypeAccess().getConstraintsAssignment_8_0_0(), "rule__SerivceType__ConstraintsAssignment_8_0_0");
			builder.put(grammarAccess.getSerivceTypeAccess().getNetworkPortsAssignment_8_0_1_1(), "rule__SerivceType__NetworkPortsAssignment_8_0_1_1");
			builder.put(grammarAccess.getSerivceTypeAccess().getNetworkPortsAssignment_8_1_2_1(), "rule__SerivceType__NetworkPortsAssignment_8_1_2_1");
			builder.put(grammarAccess.getSerivceTypeAccess().getImplementedByAssignment_12_3(), "rule__SerivceType__ImplementedByAssignment_12_3");
			builder.put(grammarAccess.getSerivceTypeAccess().getImplementedByAssignment_12_4_1(), "rule__SerivceType__ImplementedByAssignment_12_4_1");
			builder.put(grammarAccess.getSerivceTypeAccess().getConstraintsAssignment_13_2(), "rule__SerivceType__ConstraintsAssignment_13_2");
			builder.put(grammarAccess.getSoftwarePackageAccess().getNameAssignment_0(), "rule__SoftwarePackage__NameAssignment_0");
			builder.put(grammarAccess.getSoftwarePackageAccess().getInstallStartScriptAssignment_4(), "rule__SoftwarePackage__InstallStartScriptAssignment_4");
			builder.put(grammarAccess.getSoftwarePackageAccess().getConstraintsAssignment_7_1(), "rule__SoftwarePackage__ConstraintsAssignment_7_1");
			builder.put(grammarAccess.getPortsConstraintAccess().getExpressionAssignment_1(), "rule__PortsConstraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getPortsConstraintAccess().getExpressionAssignment_3(), "rule__PortsConstraint__ExpressionAssignment_3");
			builder.put(grammarAccess.getMultiplicityExpressionAccess().getMultiplicityOperatorAssignment(), "rule__MultiplicityExpression__MultiplicityOperatorAssignment");
			builder.put(grammarAccess.getPortsExpressionAccess().getAttributeNameAssignment(), "rule__PortsExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getNetworkPortAccess().getPortNameAssignment_0(), "rule__NetworkPort__PortNameAssignment_0");
			builder.put(grammarAccess.getNetworkPortAccess().getProtocolAssignment_4(), "rule__NetworkPort__ProtocolAssignment_4");
			builder.put(grammarAccess.getNetworkPortAccess().getPortNumberAssignment_7(), "rule__NetworkPort__PortNumberAssignment_7");
			builder.put(grammarAccess.getNetworkPortAccess().getHostPortAssignment_10(), "rule__NetworkPort__HostPortAssignment_10");
			builder.put(grammarAccess.getNetworkTypeAccess().getNameAssignment_2_2(), "rule__NetworkType__NameAssignment_2_2");
			builder.put(grammarAccess.getNetworkTypeAccess().getTagsAssignment_5_1(), "rule__NetworkType__TagsAssignment_5_1");
			builder.put(grammarAccess.getNetworkTypeAccess().getConstraintsAssignment_10_1(), "rule__NetworkType__ConstraintsAssignment_10_1");
			builder.put(grammarAccess.getConstraintAccess().getExpressionAssignment_1(), "rule__Constraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getConstraintAccess().getExpressionAssignment_3_0(), "rule__Constraint__ExpressionAssignment_3_0");
			builder.put(grammarAccess.getConstraintAccess().getOperatorAssignment_3_1_0(), "rule__Constraint__OperatorAssignment_3_1_0");
			builder.put(grammarAccess.getConstraintAccess().getExpressionAssignment_3_1_2(), "rule__Constraint__ExpressionAssignment_3_1_2");
			builder.put(grammarAccess.getAttributeExpressionAccess().getAttributeNameAssignment(), "rule__AttributeExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getNameAssignment_4(), "rule__NetworkLinksType__NameAssignment_4");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getTagsAssignment_7_1(), "rule__NetworkLinksType__TagsAssignment_7_1");
			builder.put(grammarAccess.getNetworkLinksTypeAccess().getConstraintsAssignment_12_1(), "rule__NetworkLinksType__ConstraintsAssignment_12_1");
			builder.put(grammarAccess.getNetworkClassConstraintAccess().getExpressionAssignment_0_0(), "rule__NetworkClassConstraint__ExpressionAssignment_0_0");
			builder.put(grammarAccess.getNetworkClassConstraintAccess().getExpressionAssignment_0_2(), "rule__NetworkClassConstraint__ExpressionAssignment_0_2");
			builder.put(grammarAccess.getNetworkClassConstraintAccess().getOperatorAssignment_1_0(), "rule__NetworkClassConstraint__OperatorAssignment_1_0");
			builder.put(grammarAccess.getNetworkClassConstraintAccess().getExpressionAssignment_1_2(), "rule__NetworkClassConstraint__ExpressionAssignment_1_2");
			builder.put(grammarAccess.getNetworkClassEnumExpressionAccess().getValueAssignment(), "rule__NetworkClassEnumExpression__ValueAssignment");
			builder.put(grammarAccess.getNetworkClassExpressionAccess().getAttributeNameAssignment(), "rule__NetworkClassExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getExpressionAssignment_0_0(), "rule__BandwidthConstraint__ExpressionAssignment_0_0");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getExpressionAssignment_0_2_0(), "rule__BandwidthConstraint__ExpressionAssignment_0_2_0");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getOperatorAssignment_1_0(), "rule__BandwidthConstraint__OperatorAssignment_1_0");
			builder.put(grammarAccess.getBandwidthConstraintAccess().getExpressionAssignment_1_2(), "rule__BandwidthConstraint__ExpressionAssignment_1_2");
			builder.put(grammarAccess.getBandwidthExpressionAccess().getAttributeNameAssignment(), "rule__BandwidthExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getIpRangeConstraintAccess().getExpressionAssignment_0(), "rule__IpRangeConstraint__ExpressionAssignment_0");
			builder.put(grammarAccess.getIpRangeConstraintAccess().getExpressionAssignment_1(), "rule__IpRangeConstraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getRangeExpressionAccess().getExpressionAssignment_1(), "rule__RangeExpression__ExpressionAssignment_1");
			builder.put(grammarAccess.getIpRangeExpressionAccess().getAttributeNameAssignment(), "rule__IpRangeExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getNameAssignment_2_2(), "rule__VirtualNodeType__NameAssignment_2_2");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getTagsAssignment_5_1(), "rule__VirtualNodeType__TagsAssignment_5_1");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getImageNameAssignment_8_2(), "rule__VirtualNodeType__ImageNameAssignment_8_2");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getImageRegistryAssignment_9_2(), "rule__VirtualNodeType__ImageRegistryAssignment_9_2");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getReplicasAssignment_10(), "rule__VirtualNodeType__ReplicasAssignment_10");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getConstraintsAssignment_13(), "rule__VirtualNodeType__ConstraintsAssignment_13");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getConstraintsAssignment_14(), "rule__VirtualNodeType__ConstraintsAssignment_14");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getConstraintsAssignment_15(), "rule__VirtualNodeType__ConstraintsAssignment_15");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getConstraintsAssignment_16(), "rule__VirtualNodeType__ConstraintsAssignment_16");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getHostingNodeAssignment_17_2(), "rule__VirtualNodeType__HostingNodeAssignment_17_2");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getDownloadLinkAssignment_22_1(), "rule__VirtualNodeType__DownloadLinkAssignment_22_1");
			builder.put(grammarAccess.getVirtualNodeTypeAccess().getUploadLinkAssignment_25_1(), "rule__VirtualNodeType__UploadLinkAssignment_25_1");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getNameAssignment_0_2_2(), "rule__PhysicalNodeType__NameAssignment_0_2_2");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getTagsAssignment_0_5_1(), "rule__PhysicalNodeType__TagsAssignment_0_5_1");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getConstraintsAssignment_5(), "rule__PhysicalNodeType__ConstraintsAssignment_5");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getConstraintsAssignment_6(), "rule__PhysicalNodeType__ConstraintsAssignment_6");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getConstraintsAssignment_7(), "rule__PhysicalNodeType__ConstraintsAssignment_7");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getConstraintsAssignment_8(), "rule__PhysicalNodeType__ConstraintsAssignment_8");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getDownloadLinkAssignment_13_1(), "rule__PhysicalNodeType__DownloadLinkAssignment_13_1");
			builder.put(grammarAccess.getPhysicalNodeTypeAccess().getUploadLinkAssignment_16_1(), "rule__PhysicalNodeType__UploadLinkAssignment_16_1");
			builder.put(grammarAccess.getReplicasConstraintAccess().getExpressionAssignment_1(), "rule__ReplicasConstraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getReplicasConstraintAccess().getExpressionAssignment_3_0(), "rule__ReplicasConstraint__ExpressionAssignment_3_0");
			builder.put(grammarAccess.getReplicasConstraintAccess().getOperatorAssignment_3_1_0(), "rule__ReplicasConstraint__OperatorAssignment_3_1_0");
			builder.put(grammarAccess.getReplicasConstraintAccess().getExpressionAssignment_3_1_2(), "rule__ReplicasConstraint__ExpressionAssignment_3_1_2");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getExpressionAssignment_1(), "rule__RuntimesConstraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getExpressionAssignment_3_0_1(), "rule__RuntimesConstraint__ExpressionAssignment_3_0_1");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getOperatorAssignment_3_1_0(), "rule__RuntimesConstraint__OperatorAssignment_3_1_0");
			builder.put(grammarAccess.getRuntimesConstraintAccess().getExpressionAssignment_3_1_3(), "rule__RuntimesConstraint__ExpressionAssignment_3_1_3");
			builder.put(grammarAccess.getCustomExpressionAccess().getExpressionAssignment(), "rule__CustomExpression__ExpressionAssignment");
			builder.put(grammarAccess.getDiskConstraintAccess().getExpressionAssignment_1(), "rule__DiskConstraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getDiskConstraintAccess().getExpressionAssignment_3_0(), "rule__DiskConstraint__ExpressionAssignment_3_0");
			builder.put(grammarAccess.getDiskConstraintAccess().getOperatorAssignment_3_1_0(), "rule__DiskConstraint__OperatorAssignment_3_1_0");
			builder.put(grammarAccess.getDiskConstraintAccess().getExpressionAssignment_3_1_2(), "rule__DiskConstraint__ExpressionAssignment_3_1_2");
			builder.put(grammarAccess.getMemoryConsraintAccess().getExpressionAssignment_1(), "rule__MemoryConsraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getMemoryConsraintAccess().getExpressionAssignment_3_0(), "rule__MemoryConsraint__ExpressionAssignment_3_0");
			builder.put(grammarAccess.getMemoryConsraintAccess().getOperatorAssignment_3_1_0(), "rule__MemoryConsraint__OperatorAssignment_3_1_0");
			builder.put(grammarAccess.getMemoryConsraintAccess().getExpressionAssignment_3_1_2(), "rule__MemoryConsraint__ExpressionAssignment_3_1_2");
			builder.put(grammarAccess.getCpuConstraintAccess().getExpressionAssignment_1(), "rule__CpuConstraint__ExpressionAssignment_1");
			builder.put(grammarAccess.getCpuConstraintAccess().getExpressionAssignment_3_0(), "rule__CpuConstraint__ExpressionAssignment_3_0");
			builder.put(grammarAccess.getCpuConstraintAccess().getOperatorAssignment_3_1_0(), "rule__CpuConstraint__OperatorAssignment_3_1_0");
			builder.put(grammarAccess.getCpuConstraintAccess().getExpressionAssignment_3_1_2(), "rule__CpuConstraint__ExpressionAssignment_3_1_2");
			builder.put(grammarAccess.getIntegerValueExpressionAccess().getValueAssignment(), "rule__IntegerValueExpression__ValueAssignment");
			builder.put(grammarAccess.getReplicasAttributeExpressionAccess().getAttributeNameAssignment(), "rule__ReplicasAttributeExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getRuntimesAttributeExpressionAccess().getAttributeNameAssignment(), "rule__RuntimesAttributeExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getDiskAttributeExpressionAccess().getAttributeNameAssignment(), "rule__DiskAttributeExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getMemoryAttributeExpressionAccess().getAttributeNameAssignment(), "rule__MemoryAttributeExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getCpuAttributeExpressionAccess().getAttributeNameAssignment(), "rule__CpuAttributeExpression__AttributeNameAssignment");
			builder.put(grammarAccess.getTagAccess().getKeyAssignment_0(), "rule__Tag__KeyAssignment_0");
			builder.put(grammarAccess.getTagAccess().getValueAssignment_2(), "rule__Tag__ValueAssignment_2");
		}
	}
	
	@Inject
	private NameMappings nameMappings;

	@Inject
	private FogDslGrammarAccess grammarAccess;

	@Override
	protected InternalFogDslParser createParser() {
		InternalFogDslParser result = new InternalFogDslParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}

	@Override
	protected String getRuleName(AbstractElement element) {
		return nameMappings.getRuleName(element);
	}

	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}

	public FogDslGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}

	public void setGrammarAccess(FogDslGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
	public NameMappings getNameMappings() {
		return nameMappings;
	}
	
	public void setNameMappings(NameMappings nameMappings) {
		this.nameMappings = nameMappings;
	}
}
