/*
 * generated by Xtext 2.25.0
 */
package fr.imta.semafor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class FogDslUiModule extends AbstractFogDslUiModule {

	public FogDslUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
