/*
 * generated by Xtext 2.28.0
 */
package fr.imta.semafor.ui;

import com.google.inject.Injector;
import fr.imta.semafor.fogDsl.ui.internal.FogDslActivator;
import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;
import org.osgi.framework.FrameworkUtil;

/**
 * This class was generated. Customizations should only happen in a newly
 * introduced subclass. 
 */
public class FogDslExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return FrameworkUtil.getBundle(FogDslActivator.class);
	}
	
	@Override
	protected Injector getInjector() {
		FogDslActivator activator = FogDslActivator.getInstance();
		return activator != null ? activator.getInjector(FogDslActivator.FR_IMTA_SEMAFOR_FOGDSL) : null;
	}

}
