/*
 * generated by Xtext 2.28.0
 */
package fr.imta.semafor.scoping;

import org.eclipse.xtext.scoping.impl.DelegatingScopeProvider;

public abstract class AbstractFogDslScopeProvider extends DelegatingScopeProvider {
}
